### ISSUE TITLE
Retrieving the data

### ISSUE THREAD

**Issue by StefanBloemheuvel** [GT-KIM/GCN_seismic_event_classification#1]
Hi,

I stumbled upon your code recently and am interested in running your code on my machine.
However, a lot of data is missing it seems. Could you maybe share exactly in which order to run the .py files? Because the \sdc\ folders for example are not available or am i missing something?

Thanks in advance and kind regards!

**Comment by GT-KIM** [comment]
Hello,
I'm sorry to say that, but the stand-alone code is not available now.
Since the code was written to adapt to our data, you need to modify the code if you use your data.

Below is the order.
1. you prepare your own seismic event data to train/test the model with our code.

2. run codes in the generate_data folder. You should revise the code to adapt to your data,
or you prepare numpy or pytorch tensor type seismic event data(recommend).

3. run train.py file to train the model. You should change the data's path and hyperparameters.

Thanks for your interest in the code. If you have any further questions, please feel free to ask.

**Comment by StefanBloemheuvel** [comment]
Hi,

Thanks for the fast reply!

Okay so getting all the right data or adapting the code might be a bit much work for now, but i have the following questions:

- What is the reasoning about selecting 3 stations? And how many of these 3-node-graphs are created for each earthquake?
- Could you elaborate more on what these edges in these 3-node-graphs represent? So why would a station be connected to another station by either a 1 or a 0?
- how many cnn's are develeloped? Because it seems to me that each 3-stations triplet gets its own cnn or am i wrong?
- could you elaborate more on what is meant with these sentences: To extract to signal, from 5 seconds to 1 second before P wave arrival time a 30-second window is advanced in 1-second increments. For example, the waveforms from 3 stations can be represented as a graph with 3 nodes and 3 edge. 

Thanks in advance, your work is really interesting!

**Comment by GT-KIM** [comment]
Hi,

1. the number of stations can be arbitrary. However, the classification model with 3 stations is enough to reduce false alarms, in our case. We also changed the number of stations from 3 to 10, but there were no major changes. When the earthquake occurs, nearby 2 to 30 stations catch the seismic waveform clearly. We collected 30C3(If 30 stations) combinations and randomly selected 100 of them for one earthquake event.
2. The graph node has seismic waveform and the graph edge has just connectivity between the stations. When the graph passes through GCN layers, features of the connected nodes interchange information of their features. Therefore, we connected all nodes for maximum-information-interchanging. If you have semantic connectivity information between stations, you can build the graph with the connectivity. We did not have any semantic information, so we connected all of them.
3. Only one CNN branch exists. Each station pass through the same CNN layers(weight shared). For example,
station 1 --> CNN1 --> feature1 --|
station 2 --> CNN1 --> feature2 --|--> GCN layers
station 3 --> CNN1 --> feature3 --|
4. The first sentence is about the data augmentation strategy. When the P arrival time is 0s, then first we can crop the signal range [0:30]s(30s long) to get a seismic event data sample. To augment the event data, we also cropped the signal range  [-1:29]s, [-2:28]s, [-3:27]s, [-4:26]s. As a result, we can get 5x event data samples. The second sentence is about data structure. The station can be represented to the node of the graph and its connectivity can be represented to the edge of the graph. 

Thank you again and I hope your experiment goes well!

**Comment by StefanBloemheuvel** [comment]
Hi,

Thanks for the response, this helps with understanding the story better!
Could you maybe also share the output of your model? 
For example, just like this:

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 64)          36928     
=================================================================
Total params: 56,320
Trainable params: 56,320
Non-trainable params: 0
_________________________________________________________________
```

Also, you mention station 1 --> CNN1 --> feature1 --, but what would be the dimensions of feature1? Or is it just one number?

**Comment by GT-KIM** [comment]
Hello,

Below is the ModuleList of the model
feature_extraction(0 to 11) denotes CNN layers, layers(12 to 16) denotes GCN layers, and classify(17 to 21) denotes FC layers.    

    =============================================================================================
                                              Kernel Shape     Output Shape  \
    Layer                                                                      
    0_feature_extraction.Conv1d_conv1           [3, 64, 3]  [192, 64, 3000]   
    1_feature_extraction.MaxPool1d_conv1_pool            -  [192, 64, 1500]   
    2_feature_extraction.Conv1d_conv2          [64, 64, 3]  [192, 64, 1500]    
    3_feature_extraction.MaxPool1d_conv2_pool            -   [192, 64, 750]   
    4_feature_extraction.Conv1d_conv3          [64, 64, 3]   [192, 64, 750]   
    5_feature_extraction.MaxPool1d_conv3_pool            -   [192, 64, 375]   
    6_feature_extraction.Conv1d_conv4          [64, 64, 3]   [192, 64, 375]   
    7_feature_extraction.MaxPool1d_conv4_pool            -   [192, 64, 188]    
    8_feature_extraction.Conv1d_conv5          [64, 64, 3]   [192, 64, 188]   
    9_feature_extraction.Conv1d_conv6          [64, 64, 3]   [192, 64, 188]   
    10_feature_extraction.Conv1d_conv7         [64, 64, 3]   [192, 64, 188]   
    11_feature_extraction.Conv1d_conv8         [64, 64, 3]   [192, 64, 188]   
    12_layers.0.Linear_linear                  [12032, 64]        [192, 64]   
    13_layers.1.Linear_linear                     [64, 64]        [192, 64]   
    14_layers.2.Linear_linear                     [64, 64]        [192, 64]   
    15_layers.3.Linear_linear                     [64, 64]        [192, 64]   
    16_layers.4.Linear_linear                     [64, 64]        [192, 64]   
     17_classify.Linear_0                         [64, 128]        [64, 128]   
    18_classify.ReLU_1                                   -        [64, 128]   
    19_classify.Linear_2                         [128, 64]         [64, 64]   
    20_classify.ReLU_3                                   -         [64, 64]   
    21_classify.Linear_4                           [64, 3]          [64, 3]   
                                                 Params  Mult-Adds  
    Layer                                                            
    0_feature_extraction.Conv1d_conv1             640.0     1.728M  
    1_feature_extraction.MaxPool1d_conv1_pool         -          -  
    2_feature_extraction.Conv1d_conv2           12.352k    18.432M  
    3_feature_extraction.MaxPool1d_conv2_pool         -          -  
    4_feature_extraction.Conv1d_conv3           12.352k     9.216M  
    5_feature_extraction.MaxPool1d_conv3_pool         -          -  
    6_feature_extraction.Conv1d_conv4           12.352k     4.608M  
    7_feature_extraction.MaxPool1d_conv4_pool         -          -  
    8_feature_extraction.Conv1d_conv5           12.352k  2.310144M  
    9_feature_extraction.Conv1d_conv6           12.352k  2.310144M  
    10_feature_extraction.Conv1d_conv7          12.352k  2.310144M  
    11_feature_extraction.Conv1d_conv8          12.352k  2.310144M  
    12_layers.0.Linear_linear                  770.112k   770.048k  
    13_layers.1.Linear_linear                     4.16k     4.096k  
    14_layers.2.Linear_linear                     4.16k     4.096k  
    15_layers.3.Linear_linear                     4.16k     4.096k  
    16_layers.4.Linear_linear                     4.16k     4.096k  
    17_classify.Linear_0                          8.32k     8.192k  
    18_classify.ReLU_1                                -          -  
    19_classify.Linear_2                         8.256k     8.192k  
    20_classify.ReLU_3                                -          -  
    21_classify.Linear_4                          195.0      192.0  
    ---------------------------------------------------------------------------------------------
    Totals
    Total params            890.627k
    Trainable params        890.627k
    Non-trainable params         0.0
    Mult-Adds             44.027584M
    =============================================================================================

Note that batch size = 64.
the output size of the line 11 is [192, 64, 188]. After that the feature is flattened then shape is [192, 12032].
Next, in the first GCN layer(line 12), [192, 12032] is reshaped to [64, 3, 12032], which is [Batch size, # of nodes, feature size], and [64, 3, 12032] is squeezed to [64, 3, 64] by GCN and reshaped to [192, 64] = [Batch size * # of nodes, features size].
Therefore, the feature1's size is [192, 12032] (or [64, 3, 12032]) = [batch size * # of nodes, feature size].

**Comment by StefanBloemheuvel** [comment]
Thanks for the reply, this makes thing a lot clearer!

**Comment by jiangfeng-strathclyde** [comment]
Hi Dear

Really insteresting work, however, I find some issues when I implement on my dataset.

1. Could you provide how you save your data and their dimensionality?
I suppose that three different types of signals were saved inside of three folders named as 0, 1, 2. Did you save each event as one npy file? For each npy file dim = [a,b,c], where a is the number of stations for each event, b = 3000 feature length, and c = 3 for channel. However, feature = feature[:3,:,:], seems like only first three stations were used to bulid the graph?

Many thanks

**Comment by GT-KIM** [comment]
Hello,

1. We saved one augmented signal, which is collected from arbitrary 3 stations, as one npz file. one npz file has 'data' and 'label' array and the shape of 'data' is [3, 3000, 3] = [# of stations, waveform length, # of channels(ENZ)]. The 'data' array is reshaped into [3, 3, 3000] and used to the feature of the graph with g.ndata['h'] = feature. Please refer to __getitem__ function.
feature = feature[:3,:,:] line can be removed if you have 3 stations per event. Since we had 10 stations in the one npz file and just selected 3 stations of them, we added this line.

Thank you.

**Comment by StefanBloemheuvel** [comment]
Hi again,

I am trying to implement your model in Tensorflow since I have a lot of issues with getting pytorch to work.

I receive the error that the input of the first maxpooling1d layer is incompatible with the first 1dcnn layer. The maxpool1d layer expected ndim=3, but received 4 (with my data which consists of (n_earthquakes, nodes,time_serie,dimensions). This must be due to the maxpooling1d layer since I do not face this error on my own model version (without max pooling).

```
ValueError: Input 0 of layer "max_pooling1d" is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 39, 1000, 64)
```

The issue could be due to some terminology differences between pytorch and keras/tensorflow, because what I do to replicate your model is:

```
conv1 = layers.Conv1D(filters=64, kernel_size=3, strides=1,padding='same',  activation='relu') (wav_input)
conv1 = layers.MaxPooling1D(pool_size=3, strides=2)(conv1)
```

In pytorch, a conv1d is made by : torch.nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, padding=0). In your code, you create the layers by:

```
nn.Conv1d(3, 64, 3, 1, 1)
```
meaning you have in_channels=3, out_channels=3, kernel_size=3, stride=1 and padding=1. However, I do not see you mention padding anywhere in your paper?
It there some difference in the way that batches are used in Pytorch such that this maxpool1d is giving me this error?

Kind regards and hopefully we can find the error here! Because your work is really interesting :)

Stefan

**Comment by GT-KIM** [comment]
Hello,

I think that you firstly reshape the inputs of the feature extraction CNN layers from (batch, # of nodes, channels, time_series) to (batch * # of nodes, channels, time_series) (in PyTorch) because they are weight-shared. After passing 1D CNN layers, reshaping again from (batch * # of nodes, time_series, channels) to (batch, # of nodes, time_series, channels). Now, the features can be passed through GCN layers. (note that Conv1d and maxpooling1D need (batch, channel, feature)(ndim=3) and GCN layer need (batch, node, channel, feature)(ndim=4).) 

In pytorch, nn.Conv1d has nn.Conv1d(in_channels, out_channels, kernel_size, stride, padding) arguments. So, nn.Conv1d(3, 64, 3, 1, 1) means in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1. The kernel size=3 and padding=1 setting is equvalent to kernel_size=3, padding='same'. I think your replication is correct.

Meanwhile, the implementation may use graph convolution layers in the DGL library, which is for the PyTorch environment. I don't know how to implement the graph convolution layer in Tensorflow.

Thank you.
